BEGIN;
--
-- Create model Address
--
CREATE TABLE "hr_address" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "address_line1" varchar(100) NOT NULL, "address_line2" varchar(100) NULL, "city" varchar(100) NOT NULL, "zip_code" integer NOT NULL);
--
-- Create model BasicInfo
--
CREATE TABLE "hr_basicinfo" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "email" varchar(254) NOT NULL);
--
-- Create model Contract
--
CREATE TABLE "hr_contract" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "hiring_date" date NOT NULL, "job_title" varchar(100) NOT NULL);
--
-- Create model Team
--
CREATE TABLE "hr_team" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL);
--
-- Create model Employee
--
CREATE TABLE "hr_employee" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "is_manager" boolean NOT NULL, "address_id" bigint NOT NULL UNIQUE, "basic_info_id" bigint NOT NULL UNIQUE, "contract_id" bigint NOT NULL UNIQUE, "manager_id" bigint NULL, "team_id" bigint NULL);
ALTER TABLE "hr_employee" ADD CONSTRAINT "hr_employee_address_id_e8ea4fcb_fk_hr_address_id" FOREIGN KEY ("address_id") REFERENCES "hr_address" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "hr_employee" ADD CONSTRAINT "hr_employee_basic_info_id_1018721f_fk_hr_basicinfo_id" FOREIGN KEY ("basic_info_id") REFERENCES "hr_basicinfo" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "hr_employee" ADD CONSTRAINT "hr_employee_contract_id_d9a9d71a_fk_hr_contract_id" FOREIGN KEY ("contract_id") REFERENCES "hr_contract" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "hr_employee" ADD CONSTRAINT "hr_employee_manager_id_e98ea225_fk_hr_employee_id" FOREIGN KEY ("manager_id") REFERENCES "hr_employee" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "hr_employee" ADD CONSTRAINT "hr_employee_team_id_ff63a1e5_fk_hr_team_id" FOREIGN KEY ("team_id") REFERENCES "hr_team" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "hr_employee_manager_id_e98ea225" ON "hr_employee" ("manager_id");
CREATE INDEX "hr_employee_team_id_ff63a1e5" ON "hr_employee" ("team_id");
COMMIT;
